//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTrackingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public int fldEntryId { get; set; }
        public int fldTaskId { get; set; }
        public System.DateTime fldClockIn { get; set; }
        public Nullable<System.DateTime> fldClockOut { get; set; }
        public string fldUserId { get; set; }
        public Nullable<double> fldHours { get; set; }
        public Nullable<decimal> fldEarning { get; set; }
    
        public virtual TTUser TTUser { get; set; }
        public virtual Task Task { get; set; }
    }
}
