//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTrackingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayPeriod
    {
        public PayPeriod()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int fldPayPeriodId { get; set; }
        public string fldPayPeriodName { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
