//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTrackingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int fldScheduleId { get; set; }
        public int fldClockInYear { get; set; }
        public int fldClockInMonth { get; set; }
        public int fldClockInDay { get; set; }
        public System.TimeSpan fldClockInTime { get; set; }
        public string fldUserId { get; set; }
        public int fldClockOutYear { get; set; }
        public int fldClockOutMonth { get; set; }
        public int fldClockOutDay { get; set; }
        public int fldClockOutTime { get; set; }
    
        public virtual TTUser TTUser { get; set; }
    }
}
