//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTrackingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.TaskTags = new HashSet<TaskTag>();
            this.TagFilters = new HashSet<TagFilter>();
        }
    
        public int fldTagId { get; set; }
        public string fldTagName { get; set; }
    
        public virtual ICollection<TaskTag> TaskTags { get; set; }
        public virtual ICollection<TagFilter> TagFilters { get; set; }
    }
}
