//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTrackingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Entries = new HashSet<Entry>();
            this.TaskTags = new HashSet<TaskTag>();
        }
    
        public int fldTaskId { get; set; }
        public string fldTaskName { get; set; }
        public string fldTaskDescription { get; set; }
        public string fldTaskLocation { get; set; }
        public Nullable<double> fldEstimagedHours { get; set; }
        public Nullable<double> fldHourlyRate { get; set; }
        public Nullable<int> fldPayPeriodId { get; set; }
        public int fldProjectId { get; set; }
        public Nullable<System.DateTime> fldStartDate { get; set; }
        public Nullable<System.DateTime> fldEndDate { get; set; }
        public Nullable<bool> fldIsDone { get; set; }
        public Nullable<bool> fldIsPaid { get; set; }
        public Nullable<bool> fldAutoClock { get; set; }
    
        public virtual ICollection<Entry> Entries { get; set; }
        public virtual PayPeriod PayPeriod { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<TaskTag> TaskTags { get; set; }
    }
}
