//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTrackingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTUser
    {
        public TTUser()
        {
            this.Entries = new HashSet<Entry>();
            this.Schedules = new HashSet<Schedule>();
            this.Projects = new HashSet<Project>();
        }
    
        public string fldUserEmail { get; set; }
        public string fldPassword { get; set; }
        public string fldFirstName { get; set; }
        public string fldFamilyName { get; set; }
        public Nullable<System.DateTime> fldDOB { get; set; }
        public string fldPosition { get; set; }
        public string fldMobile { get; set; }
        public string fldphoto { get; set; }
        public Nullable<bool> fldIsActive { get; set; }
    
        public virtual ICollection<Entry> Entries { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
